### ISSUE TITLE
How to define a  primary type, like Boolean or Int or String?

### ISSUE THREAD

**Issue by ash0080** [cj/jsgql#2]
Now, if no fields: 
It will throw an error 

```
GraphQLError: Syntax Error: Expected Name, found }
```

```
mutation {
  deleteTask(id:"5a64831f23182d0014e40f2d") 
}
```
```
{
  "data": {
    "deleteTask": true
  }
}
```

**Comment by ash0080** [comment]
#3 fixed

**Comment by cj** [comment]
@ash0080 thank you for finding this bug and I appreciate your pull request #3 !  It was actually a lot simpler to fix, `processFields` just needed to return `null` instead.  I also added a test https://github.com/cj/jsgql/commit/077458a2f675d6cad2b5c15d333711a7334405a0.  Let me know if that works for you!

**Comment by ash0080** [comment]
Sorry but no, 
if return type is a primary type, graphql-tag doesn't accept an empty {} after the query body now, 
it should be nothing there
```
gql`
getObj(){
 id
}
`
```

```
qql`
getBoolean()  // no curly brackets  here
`
```

**Comment by cj** [comment]
@ash0080 can you show me the jsgql you are using plus the current output and then the output you expect.  That would really help, thank you!

**Comment by cj** [comment]
If there are no fields, I should probably throw an error as graphql always requires a minimum of one field to be sent, even on a mutation.

**Comment by ash0080** [comment]
Graphql shouldn't throw an error if return is a primary type, check my snapshots

![2018-01-26 12 02 12](https://user-images.githubusercontent.com/2803210/35398159-3b8ed566-022c-11e8-9a9c-26ce48b3840f.png)
![2018-01-26 12 13 31](https://user-images.githubusercontent.com/2803210/35398819-cca4548a-022d-11e8-9fa3-765707bd5e33.png)

And if you put an empty curly brackets, it will throw an error
What you understood is exactly the opposite
![2018-01-26 12 19 32](https://user-images.githubusercontent.com/2803210/35399174-a15ec03e-022e-11e8-9961-276c513ed48e.png)

```
// type defines
# isAdmin
type Query {
    countProducts: Int!  // here!!
    getAvaliableProducts: [Product]!
    getProduct(id:ID!): Product
}
```

```
// This is codes worked with my fixed version

const deleteAllMyTaskMut = {
  type: 'mutation',
  method: 'deleteTask'
}

console.dir(jsgql(deleteAllMyTaskMut))

// outputs

{ kind: 'Document',
  definitions: 
   [ { kind: 'OperationDefinition',
       operation: 'mutation',
       name: undefined,
       variableDefinitions: [],
       directives: [],
       selectionSet: [Object] } ],
  loc: 
   Loc {
     start: 0,
     end: 49,
     source: 
      Source {
        body: '\n    mutation {\n        deleteTask(id:"1")\n    }\n',
        name: 'GraphQL request',
        locationOffset: [Object] } } }
{ kind: 'Document',
  definitions: 
   [ { kind: 'OperationDefinition',
       operation: 'mutation',
       name: undefined,
       variableDefinitions: [],
       directives: [],
       selectionSet: [Object] } ],
  loc: 
   Loc {
     start: 0,
     end: 30,
     source: 
      Source {
        body: 'mutation  {\n    deleteTask\n  }',
        name: 'GraphQL request',
        locationOffset: [Object] } } }

```

**Comment by cj** [comment]
@ash0080 I know that might be working, but it is technically invalid GraphQL schema.  Mutations and Queries always require a sub-selection i.e. for that first example it should be:

```graphql
mutation {
  updateAirlineInfo(
    portCode: 1
    flightCode: "AC123"
    time: "2018-01-25T15:54:34.875Z"
    direct: true
  ) {
    id
  }
}
```

For the count one, you should be doing something like this https://www.graph.cool/docs/reference/graphql-api/query-api-nia9nushae#type-aggregation-queries, another way would be to use the relay syntax, this blog post does a pretty good job of explaining it https://medium.com/workflowgen/graphql-api-pagination-implementation-88dba6a061af.

https://www.howtographql.com/ is also a great resource and if you wanted to start playing around with your own fully structured graphql api in minutes https://graph.cool is great!  Github also has an explorer you can check out https://developer.github.com/v4/explorer/.

**Comment by ash0080** [comment]
Sorry, but I didn't see anything about return a scalar type is illegal.
Actually, I saw an example before from @leebyron in a question post like 'how to do something without  database operation?',  in that post he suggest return an Boolean directly.

so I think this syntax is legal, and you can found, it works well with graphiQL,  graphql-tag and all long list graphql ecosystem.

Anyway, Maybe you shouldn't add a limit before the graphql-tag, right? At least, the graphql-tag still support this syntax.

**Comment by cj** [comment]
@ash0080 looks like I was mistaken and you can actually have no fields at the root!  I just don't think it's common practise from what I've seen.  I've updated it, so now it should work how you need!  :)

**Comment by ash0080** [comment]
Besides, in last pull-request, I fixed the name 'undefined' error, please consider it
```
export default ({ type, name = '', variables, method, fields, types, methodArgs }) => {
```
